# Generated by Django 4.1.7 on 2023-02-24 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dob", models.DateTimeField()),
                ("phone_number", models.CharField(max_length=13)),
                ("address_line1", models.CharField(max_length=255)),
                ("suburb", models.CharField(help_text="Suburb/Town", max_length=255)),
                ("city", models.CharField(max_length=50)),
                (
                    "province",
                    models.CharField(
                        help_text="State: Gauteng, Free State, etc...", max_length=50
                    ),
                ),
                ("postal_code", models.CharField(blank=True, max_length=13)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
