# Generated by Django 4.1.7 on 2023-02-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_profile_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="latitude",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="longitude",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
