# Generated by Django 4.1.7 on 2023-02-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_latitude_profile_longitude"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="dob",),
    ]
